plugins {
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation project(':core')
    implementation 'com.ibm.icu:icu4j:78.1'
}

application {
    mainClass = 'com.matrix.p0.cli.Main'
}

tasks.named('run') {
    workingDir = rootProject.projectDir
}
