plugins {
    id 'java-library'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    api 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

sourceSets {
    test {
        resources.srcDir rootProject.file('gold')
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

